Repository koetjeengdjalanan/nilakandi, pull requests merged in 2025-03, with the labels that each got.

#7 Handling an Absurd Azure Python SDK
  .devcontainer/python/devcontainer.json
  config/settings/celery.py
  nilakandi/azure/__int__.py
  nilakandi/azure/api/__init__.py
  nilakandi/azure/api/services.py
  nilakandi/azure/models.py
  nilakandi/helper/azure_api.py
  nilakandi/helper/miscellaneous.py
  nilakandi/management/commands/populate_db.py
  nilakandi/models.py
  nilakandi/tasks.py
  nilakandi/views.py
  requirements.txt
Labels: good first issue

#13 Bugfix/pivot-column-sort
  nilakandi/helper/serve_data.py
  nilakandi/templates/base.html
  nilakandi/templates/home.html
  nilakandi/templates/navbar.html
  nilakandi/templates/servicesCost.html
  nilakandi/templates/subscriptions.html
Labels: bug

#14 Hotfix/values-too-long-string
  nilakandi/models.py
Labels: bug

#8 Feature/logging
  .devcontainer/db/devcontainer.json
  .devcontainer/python/devcontainer.OLD
  .devcontainer/python/devcontainer.json
  .docker/docker-compose.yml
  .github/dependabot.yml
  .gitignore
  config/asgi.py
  config/django/base.py
  config/django/local.py
  config/django/production.py
  config/django/test.py
  config/env.py
  config/settings/azure.py
  config/settings/celery.py
  config/settings/logging.py
  config/settings/redis.py
  config/urls.py
  config/wsgi.py
  manage.py
  nilakandi/admin.py
  nilakandi/apps.py
  nilakandi/helper/azure_api.py
  nilakandi/helper/serve_data.py
  nilakandi/management/commands/grab_from_azure.py
  nilakandi/management/commands/populate_db.py
  nilakandi/models.py
  nilakandi/signals.py
  nilakandi/tasks.py
  nilakandi/templates/base.html
  nilakandi/templates/home.html
  nilakandi/templates/navbar.html
  nilakandi/templates/servicesCost.html
  nilakandi/templates/subscriptions.html
  nilakandi/templates/subsreport.html
  nilakandi/tests.py
  nilakandi/urls.py
  nilakandi/views.py
Labels: enhancement

#15 Let there be Harmony between us Dev 😇
  .devcontainer/db/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/python/devcontainer.OLD
  .devcontainer/python/devcontainer.json
  .docker/docker-compose.yml
  .docker/web/Dockerfile
  .dockerignore
  .gitattributes
  .github/dependabot.yml
  .gitignore
  README.md
  config/asgi.py
  config/django/base.py
  config/django/local.py
  config/django/production.py
  config/django/test.py
  config/env.py
  config/settings/azure.py
  config/settings/celery.py
  config/settings/redis.py
  config/urls.py
  config/wsgi.py
  manage.py
  nilakandi/admin.py
  nilakandi/apps.py
  nilakandi/helper/azure_api.py
  nilakandi/helper/serve_data.py
  nilakandi/management/commands/grab_from_azure.py
  nilakandi/management/commands/populate_db.py
  nilakandi/models.py
  nilakandi/tasks.py
  nilakandi/templates/base.html
  nilakandi/templates/home.html
  nilakandi/templates/navbar.html
  nilakandi/templates/servicesCost.html
  nilakandi/templates/subscriptions.html
  nilakandi/templates/subsreport.html
  nilakandi/tests.py
  nilakandi/urls.py
  nilakandi/views.py
  pyproject.toml
Labels: enhancement

#9 Feature/vm and bill api
  .devcontainer/python/devcontainer.json
  .gitignore
  config/django/base.py
  config/settings/celery.py
  nilakandi/helper/azure_api.py
  nilakandi/helper/serve_data.py
  nilakandi/management/commands/grab_from_azure.py
  nilakandi/management/commands/populate_db.py
  nilakandi/models.py
  nilakandi/tasks.py
  nilakandi/templates/base.html
  nilakandi/templates/home.html
  nilakandi/views.py
  requirements.txt
Labels: enhancement

#16 Enhance Azure API integration and improve project structure
  .devcontainer/docker-compose.yml
  .devcontainer/python/devcontainer.json
  .docker/docker-compose.yml
  .docker/web/Dockerfile
  .dockerignore
  .gitattributes
  .gitignore
  README.md
  config/django/base.py
  config/settings/celery.py
  config/settings/logging.py
  nilakandi/apps.py
  nilakandi/helper/azure_api.py
  nilakandi/helper/serve_data.py
  nilakandi/management/commands/grab_from_azure.py
  nilakandi/management/commands/populate_db.py
  nilakandi/models.py
  nilakandi/signals.py
  nilakandi/tasks.py
  nilakandi/templates/base.html
  nilakandi/templates/home.html
  nilakandi/templates/navbar.html
  nilakandi/templates/servicesCost.html
  nilakandi/templates/subscriptions.html
  pyproject.toml
  requirements.txt
Labels: bug, enhancement
